name: Deploy Strapi API on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: yarn build  

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem  

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/strapi/directory  # Adjust path as per your setup
            git pull origin main  # Pull latest changes from your repository
            npm install --production  # Install production dependencies
            npm run build  # Build your Strapi application
            pm2 restart ecosystem.config.js --env production  # Restart Strapi using PM2
