name: Deploy Strapi API on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build  

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem  

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Free up disk space by removing unnecessary files
            sudo rm -rf /tmp/*

            # Install Node.js and npm on the EC2 instance
            sudo apt-get update
            sudo apt-get install -y nodejs npm

            # Create a directory for the application
            mkdir -p /home/ubuntu/my-strapi-project
            cd /home/ubuntu/my-strapi-project

            # Transfer the build artifacts from the GitHub Actions environment
            scp -o "StrictHostKeyChecking=no" -r $GITHUB_WORKSPACE/* ubuntu@${EC2_HOST}:/home/ubuntu/my-strapi-project

            # Install dependencies and build the application
            npm install
            npm run build

            # Install PM2
            sudo npm install -g pm2

            # Start the application using PM2
            pm2 startup ubuntu
            pm2 startOrRestart my-strapi-project
