name: Deploy Strapi API on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build  

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install git, Node.js, and npm on the EC2 instance
            sudo apt-get update
            sudo apt-get install -y git nodejs npm

            # Create a directory for the application if it doesn't exist
            mkdir -p /home/ubuntu/my-strapi-project
            cd /home/ubuntu/my-strapi-project

            # Clone the repository if it doesn't exist, otherwise pull the latest changes
            if [ ! -d ".git" ]; then
              git clone https://github.com/your-username/your-repo.git .
            else
              git pull origin main
            fi

            # Install dependencies and build the application
            npm install
            npm run build

            # Start the application using PM2
            sudo npm install -g pm2
            pm2 startup ubuntu
            pm2 start ecosystem.config.js --env production  # Assuming you have an ecosystem.config.js file for PM2

            # Save the PM2 process list and startup script
            pm2 save

